### ISSUE TITLE
Reboot

### ISSUE THREAD

**Issue by skelletR** [kdrag0n/safetynet-fix#124] opened 2021-11-20 15:55 UTC
Hi, i have Sony Xperia Z5 android 7.1.1 latest canary, i flash the 2.2.0 version my phone open and after few seconds do it itself reboot and the same again until i delete from twrp the module

**Comment by osm0sis** [comment] 2021-12-21 02:47
I can't imagine Android 7.1.1 having issues with hardware attestation, so you could probably just use MagiskHidePropsConfig instead.

You also haven't provided any logs to help fix your issue, so until you do this should be closed.

**Comment by kdrag0n** [comment] 2021-12-21 23:15
Duplicate of #127

**Closed by kdrag0n** 2021-12-21 23:15 UTC
