### ISSUE TITLE
Requirement for riru causes root detection problem in chase app

### ISSUE THREAD

**Issue by dhammel** [kdrag0n/safetynet-fix#104] opened 2021-10-14 16:06 UTC
Hello,

I have latest version of magisk, riru and safteynet-fix module.

When I downgraded to latest version of safteynet-fix that didn't require riru and then delete riru and reboot, i managed to get chase banking app to believe my device isn't rooted, after installing riru and rebooting chase then detects root.

I need the safteynet-fix module installed to bypass hardware attestation, so deleting it outright, safteyney will fail cts.

With either version with or without riru so far, safteynet completely passes.

Chase takes things a step further by checkng for magisk manager package, so I have to hide it as well.

Is there a reason for switching to riru?

Apparently google play services has an extra check for modified zygote process which I believe chase is utilizing to check for root, according to some research (not sure of the accuracy on it though).

I've enabled all processes of chase in magisk hide, hid magisk manager, temporarily moved any magisk related files in root of internal storage to pc (searched root of storage for keyword 'magisk' to be sure nothing found), checked safteynet which passes success, cleared storage of chase and re-signed in.

Other apps which check for root such as netflix have no issues, my other banking app (Discover) doesn't even check for root.

**Comment by kdrag0n** [comment] 2021-10-17 13:07
The migration to Riru made it possible to fix several issues:

- Compatibility issues with heavily-modded OEM ROMs
- Crashes caused by blocking non-SafetyNet usage of key attestation
- Issues caused by changing the device model name globally

Not much can be done about this issue for now. However, I've taken a look at Zygisk and it looks like it will be mostly resistant to in-process detection as per the API documentation, so this should be fixed when we switch to Zygisk.

**Closed by kdrag0n** 2021-10-17 13:07 UTC
