### ISSUE TITLE
S9 plus failed cts and playstore

### ISSUE THREAD

**Issue by handy1977** [kdrag0n/safetynet-fix#67] opened 2021-06-24 11:59 UTC
I have installed latest magisk 23. Android 10. My s9 plus has stock firmware from sammy website. My phone has failed cts and playstore device not certified. Can you please help how I can fix this so I can use Google pay.thank you.

**Comment by kdrag0n** [comment] 2021-06-27 07:20
Duplicate of #32.

**Closed by kdrag0n** 2021-06-27 07:20 UTC
