### ISSUE TITLE
Google account settings crash after module enabled

### ISSUE THREAD

**Issue by dorawei** [kdrag0n/safetynet-fix#172] opened 2022-03-27 18:00 UTC
**Describe the bug**
After installing safetynet-fix-v2.2.1.zip (v2.2.1 (Zygisk)) Google account settings simply crash 

**To reproduce**
1. Go to 'Settings'
2. Click on 'Google'
3. Settings crash/No response (After uninstalling Google Play Services update, sometimes it says Google Play Services kept stopping)

**Expected behavior**
After factory reset and testing several modules, finally figured out that when satetynet-fix enabled, the account settings for Google would go crash, and removing account would result in no response, if signed out from the web, sigining-in simply won't work and keeps crashing.

Disable the module would bring the account setting page back without crashing. 

**Device info**
Device model: Pixel 4a 5g
Android version: 12 (SP2A.220305.012)
ROM name/version: bramble-sp2a.220305.012

**Logs**
attached

**Additional context**

**Comment by kdrag0n** [comment] 2022-03-28 22:47
Duplicate of #163

**Closed by kdrag0n** 2022-03-28 22:47 UTC
Labels: bug
