### ISSUE TITLE
Safteynet check fails 

### ISSUE THREAD

**Issue by gastrodon** [kdrag0n/safetynet-fix#38] opened 2021-04-22 19:13 UTC
![Screenshot_20210422-151052](https://user-images.githubusercontent.com/10934565/115772445-1d22ee00-a37d-11eb-87ce-d744c1e2cc37.png)

Pixel 4a, Android 11
safteynet-fix 1.1.1
magiskhide props 5.4.0-v125
magisk 22.1

**Comment by Didgeridoohan** [comment] 2021-04-22 19:55
That's not a fail. It's the app not being able to connect to Google's servers. The API key John used for the Magisk app has been revoked and a new one will be used in future Magisk releases...

There's nothing wrong.

**Comment by kdrag0n** [comment] 2021-04-22 19:55
Duplicate of #37.

**Closed by kdrag0n** 2021-04-22 19:55 UTC

**Comment by gastrodon** [comment] 2021-04-23 14:26
It appears that safteynet is also failing in other apps, like Google play

**Comment by gastrodon** [comment] 2021-04-28 21:10
@kdrag0n this isn't just magisk failing, should this be reopened?
