### ISSUE TITLE
MIUI can't use third party ttf

### ISSUE THREAD

**Issue by Taylorc0804** [kdrag0n/safetynet-fix#215] opened 2022-08-22 06:03 UTC
If MIUI uses 3rd party fonts, I need to install another magisk module to load normally。But if I use this module at the same time, Google Play Services will FC。

Here is the link to this module.
https://yukonga.lanzoub.com/iSxAP07pu05i

**Comment by kdrag0n** [comment] 2022-10-05 16:32
Duplicate of #163

**Closed by kdrag0n** 2022-10-05 16:32 UTC
