### ISSUE TITLE
This module breaks my a40

### ISSUE THREAD

**Issue by ChameleonCiskoCZ** [kdrag0n/safetynet-fix#72] opened 2021-07-20 07:44 UTC
when i install this module, everything works, but after i write my password, phone starts booting again and i need to do that several times because sometimes it takes longer, so i can run into magisk and disable it

**Comment by kdrag0n** [comment] 2021-07-24 01:28
Duplicate of #32

**Closed by kdrag0n** 2021-07-24 01:28 UTC
