### ISSUE TITLE
mod causing full phone lockup

### ISSUE THREAD

**Issue by pbanj** [kdrag0n/safetynet-fix#60] opened 2021-06-09 22:19 UTC
Phones I know of it doing it are 3a, 3a xl and 4a all running stock roms. It'll mostly happen when you plug the phone in to charge, but it'll also happen seemingly at random. I thought I was the one one having this issue until I decided to ask @Skittles9823 if he had any idea why WiFi would cause a lockup as it seemed to stop if you killed WiFi and or mobile data together

![image](https://user-images.githubusercontent.com/17306233/121435087-54a92200-c94c-11eb-9119-92b1828f89b6.png)

After finding out he had the same issue I was having I decided to ask in another group and found out they were having the same problem. So I started testing, I disabled the pixel launcher like I said in the picture and it didn't lockup for a few days, then last night it did. Well I had scoop running to try and grab the crash and I wasn't able to get a log of the issue. Well it didn't catch the lockup as the entire system locked up. I was able to grab some logs after it rebooted by dumb luck, I got WiFi off apparently mid crash and it grabbed all the logs and then locked up for a few seconds but then came out of it. These are those logs.
 
[gps.zip](https://github.com/kdrag0n/safetynet-fix/files/6627125/gps.zip)

When I opened the log to read it to see if I could find whats causing it, they were all complaining about the keystore. So I asked the people I knew having the issue if they had your fix installed and they all did. One of them was using 2.0 instead of 1.1 

![image](https://user-images.githubusercontent.com/17306233/121435840-8ec6f380-c94d-11eb-9598-1ca23d981c91.png)

I figured having the logs might be helpful

**Comment by kdrag0n** [comment] 2021-06-10 19:56
It looks like Google Play Services is trying to use key attestation for other purposes and crashing when it fails, which is likely unavoidable with an approach like this. I'm not sure what causes it to do that, but I've never seen it happen on my device. I've been daily driving my ROM (which is where the workaround originated) for months with no such issues.

**Comment by salmanb** [comment] 2021-06-28 14:38
just adding this here for visibility -- I'm having this issue, as well. I created an LOS bug report for this a few weeks ago, thinking that it might be an issue with that as I did not see this on LOS17: https://gitlab.com/LineageOS/issues/android/-/issues/3498

**Comment by thakyZ** [comment] 2021-07-06 16:48
I have this issue too. I thought it may be another mod but upon factory resetting my phone and disabling everything but this mod and then patching the bootloader again, it starts to lock up still. So I am not sure what causes this, but I am on the Stable Magisk build on June build of Pixel 3's factory image.

**Comment by salmanb** [comment] 2021-07-10 03:57
Installing v2 does not seem to have made a big improvement. Still get freezes when I turn on my work profile.

**Comment by thakyZ** [comment] 2021-07-10 19:27
@salmanb Where do you get v2? I downloaded v1.2 and it makes the safety net pass way worse than with v1 because now the basic integrity doesn't even pass.

**Comment by thakyZ** [comment] 2021-08-02 22:17
> 
> 
> Installing v2 does not seem to have made a big improvement. Still get freezes when I turn on my work profile.

Yea when I first installed it, it was working, but then after a day it would still continue to freeze.

**Comment by salmanb** [comment] 2021-08-04 15:47
In the LOS bug report, someone reported that changing to another kernel seems to fix this. I've tried that, and have not seen any freezes since the switch. So, this might be a kernel config issue, rather than an issue with this mod.

**Comment by dmitry87** [comment] 2021-08-05 06:46
Locks up pixel3 on a latest Factory image (image-blueline-rq3a.210805.001.a1.zip) Gives you more time when wifi and mobile data is switched off. Magisk cannot load to remove the module. You have the option to remove all modules from adb or remove the safetynet module from safe mode.

Remove from safe mode.
1. Enter safe mode by hitting power of button
2. Select and hold power off and click ok to enter safe mode
3. In safemode magisk is disabled. So reboot back into normal mode.
4. When you boot up normally all the modules are disabled by default until next reboot.
5. Remove SafetyNet module that causing the issue

Remove from adb
1. Power off your Android device completely.
2. Connect phone to your PC with platform tools installed
2. run `adb wait-for-device shell magisk --remove-modules` from the folder with Platform Tools
3. Switch on your device

Does the issue exist for 1.2 only? If yes please disable release or add a notice until issue is fixed.

**Comment by skittles9823** [comment] 2021-08-05 06:55
> 3. run `adb wait-for-device shell magisk --remove-modules` from the folder with Platform Tools

as opposed to that, you could just run this command to only disable the specific module causingg issues.
`adb shell su -c touch /data/adb/modules/safetynet-fix/disable`

**Comment by dmitry87** [comment] 2021-08-07 06:51
Installed custom kernel https://forum.xda-developers.com/t/kernel-05-08-2021-4-9-278-kirisakura_r-3-1-0-for-pixel-3-xl-aka-bluecross.3864563/post-85432093 with Ex Kernel Manager. The issue is no longer reproduced. SafetyNet check passed. Pixel3 128Gb. Factory Image (image-blueline-rq3a.210805.001.a1.zip)

**Comment by pbanj** [comment] 2021-08-07 17:36
Hmmm wonder what it changes that the stock one doesnt

**Comment by nate2014jatc** [comment] 2021-08-08 01:19
This issue is also present on Pixel 3 XL using LineageOS 18.1 (lineage_crosshatch-userdebug 11 RQ3A.210705.001 8f057788c5). 
Will try another kernel later.

**Comment by nate2014jatc** [comment] 2021-08-08 01:48
> This issue is also present on Pixel 3 XL using LineageOS 18.1 (lineage_crosshatch-userdebug 11 RQ3A.210705.001 8f057788c5).
> Will try another kernel later.

This also seems to happen more often when I have the F-Droid privilege extension installed and enabled.

**Comment by pbanj** [comment] 2021-08-10 06:29
Custom kernel has seemed to fix it. I'm using ex

**Comment by kdrag0n** [comment] 2021-08-23 08:03
Fixed in [v2.0.0](https://kdrag0n.dev/patreon/safetynet-fix/v2.0.0?utm_source=github).

**Closed by kdrag0n** 2021-08-23 08:03 UTC

**Comment by nate2014jatc** [comment] 2021-08-23 08:35
Congratulations on the v2 milestone!
I see the file is available on your patreon.
How long do you normally have it be patreon exclusive before it hits generally available?

**Comment by kdrag0n** [comment] 2021-08-24 02:37
> Congratulations on the v2 milestone! I see the file is available on your patreon. How long do you normally have it be patreon exclusive before it hits generally available?

It's intended to be a week, but it can take longer depending on my availability at that time.
