### ISSUE TITLE
Samsung Galaxy A9 2018 (A920F)  Android 10 Updated

### ISSUE THREAD

**Issue by Navneet-Kumar-Singh** [kdrag0n/safetynet-fix#41] opened 2021-04-29 03:19 UTC
after installing this module 1.1.1 version: 
1) 1st of all always on restarting and immediately unlocking the lock screen it causes reboot of ui , but if i give some time like 20-30 seconds with screen turned on  before unlocking the phone ,the issue doesn't occur( Con: If I have emergency then I can't immediately unlock phone but have to wait for 20-30 seconds) 

2) Now after successfully unlocking by above methods , opening play store and  turning on biometric authentication for payments causes the play store to abruptly close as if force stopped ,whether i press cancel or ok after entering password for biometric authentication  ,in both cases play store closes abruptly.

3)I also noticed that after installing the module my samsung account asks for relogin again and again until I relogin.

4) now module was successful in passing cts profile(both true) , earlier hardware attestation caused partial failure of safetynet (basic still true). Google play store also shows certified.

5) this module also broke my system making it irrecoverable even after uninstalling the module,  reason is when I tried to add a new google account in settings as soon as I agreed to the Google terms of service  after entering my Google password and tapped agree, it caused permanent bootloop until I remove that added Google account  from settings by entering safe mode  after which it then reboots properly back to system. 

6)after uninstalling  the module , 
           i) issue of biometric authentication is gone
           ii) safetynet fails
           iii) but main aftereffect is that uninstall doesn't solve the reboot caused after adding new Google account 
            iv) the lockscreen reboot issue is also gone and I can Immediately unlock my device after restarting my device  without my phone again rebooting.

Thats all

I want this module to be error free, if you have taken to read this then I thank you . I hope my observation can help in improving this excellent module just some  bugs to fix. 

And yes I forgot to mention,  versions from 1.0.2 and below  only cause bootloop without even entering system, versions after 1.0.2 cause restart after I immediately unlock after a restart. Also , I  tried  the test version 2.0.0 for samsung uis and it didn't even pass safetynet, with other issues staying same.
Thank you

**Comment by kdrag0n** [comment] 2021-04-29 15:42
Duplicate of #32 and #33.

**Closed by kdrag0n** 2021-04-29 15:42 UTC

**Comment by KHOENIX** [comment] 2021-05-18 09:31
Leave a comment
