### ISSUE TITLE
Safetynet -fix crashing 

### ISSUE THREAD

**Issue by lolinajdi** [kdrag0n/safetynet-fix#63] opened 2021-06-13 12:03 UTC
Hello 
I flashed  the latest  version  of safetynet  fix on my Samsung  galaxy  s9 puls  
On Android  10
When  I flashed I can't  enter  in my phone  it stuck  on lock screen 
And also the Google  play  cursh  when  trying  to  enabling  bitromic option in Google  play 
Please  fix these  issues

**Comment by kdrag0n** [comment] 2021-06-14 19:42
Duplicate of #32.

**Closed by kdrag0n** 2021-06-14 19:42 UTC

**Comment by lolinajdi** [comment] 2021-06-14 20:16
I don't understand anything 

But this solution is work for me 

https://github.com/kdrag0n/safetynet-fix/issues/6#issuecomment-764129632
