### ISSUE TITLE
Oneplus8pro since 1 week CTS fail - Google Pay 

### ISSUE THREAD

**Issue by mxcxpx** [kdrag0n/safetynet-fix#194] opened 2022-06-25 19:34 UTC
**Describe the bug**

**To reproduce**

**Expected behavior**

**Screenshots**

**Device info**
Device model:
Android version:
ROM name/version:

**Logs**
Connect your phone to a computer and run `adb logcat > issue.log`. Attach the log file to this issue.

**Additional context**

**Checklist**
- [ ] All information is present
- [ ] Logs are attached
- [ ] I have tried installing and configuring [MagiskHide Props Config]https://github.com/Magisk-Modules-Repo/MagiskHidePropsConf)

**Comment by kdrag0n** [comment] 2022-06-28 00:47
Duplicate of #188

**Closed by kdrag0n** 2022-06-28 00:47 UTC
Labels: bug
