### ISSUE TITLE
SafetyNet-Fix 2.1 (probably also 2.1.1) breaks NGA

### ISSUE THREAD

**Issue by HennyBro** [kdrag0n/safetynet-fix#93] opened 2021-09-15 18:40 UTC
Edit: Continued Conversation is also broken by the module.

On Android 12 (probably also other Android versions & or devices) flashing the SafetyNet-Fix v2.1 breaks the New Google Assistant on the Pixel 4. It doesn't show the "Your assistant needs additional downloads." which is necessary for the New Google Assistant to operate.

It also switched the design of my phone from a seemingly outdated one to a very modern one that seems more Material You like. I don't mind that at all^^

[It might also have broken Continued Conversation from the New Google Assistant. But that could also just be the Google App beta build I'm currently using.]

**Comment by AzizKamboh** [comment] 2021-09-15 21:26
Google assistant broken on Android 11 too

**Comment by Nicolas22320** [comment] 2021-09-17 10:54
I'm in pixel 5 last update with last safety net fix and no issue with my assistant. Fully work

**Comment by vaugerbird** [comment] 2021-09-18 04:58
I'm on Pixel 4a with Android 12 B5, and my assistant has reverted to the original card style from the transparent Pixel exclusive style. Otherwise, I see no problemes.

**Comment by creeve4** [comment] 2021-09-20 19:07
I found an unintended side affect of the new bypass methods introduced in 2.1.0: my Pixel 4a running Android 11 is no longer recognized as a Pixel by Google Assistant and thus "Hey Google" is no longer available when the screen is off:

![Screenshot_20210920-121626](https://user-images.githubusercontent.com/1910130/134060046-d57c480e-671a-48a6-a2aa-b5a4d78bbc77.png)

**Comment by Photopuppet** [comment] 2021-09-23 18:42
Same issue with MIUI 12.5 with 2.1.1, Google Assistant no longer working when screen off. Would be great if this could be fixed. :)

**Comment by DavidBerdik** [comment] 2021-09-27 22:29
> I found an unintended side affect of the new bypass methods introduced in 2.1.0: my Pixel 4a running Android 11 is no longer recognized as a Pixel by Google Assistant and thus "Hey Google" is no longer available when the screen is off:

I can confirm that I am also seeing the same behavior with v2.1.0 of this module. I am not sure if it happened with v1.0.0.

**Comment by cmstew** [comment] 2021-10-17 14:50
I did a little trial and error and found that all the updates 1.2 and newer cause this problem for me.

It's a pretty minor inconvenience however since Google responded to me in the middle of unrelated conversations half the time. Lol

**Comment by DavidBerdik** [comment] 2021-10-20 02:06
That doesn't make sense to me. I have used v1.1.1 through the latest version on my phone and I still have this issue on my Pixel 3 XL.

**Comment by fishnux** [comment] 2021-10-20 02:25
> That doesn't make sense to me. I have used v1.1.1 through the latest version on my phone and I still have this issue on my Pixel 3 XL.

Ok, false alarm. It did work for a brief time, looks like NGA has some sort of cache, so it worked the first couple of times (including after a reboot).

I'm downgrading to v1.2.0 to confirm if this version is responsible for breaking the NGA. Assuming yes, these were the changes between v1.1.1 and v1.2.0:
https://github.com/kdrag0n/safetynet-fix/compare/v1.1.1...v1.2.0

**Comment by DavidBerdik** [comment] 2021-10-20 03:42
> I would guess v2.0.0 breaks NGA as it was a significant rewrite of the module

I'm guessing that @kdrag0n won't bother to fix it then, as I believe he's planning to do yet another major rewrite once Zygisk goes stable.

**Comment by kdrag0n** [comment] 2021-10-31 04:08
Fixed in [v2.1.2](https://kdrag0n.dev/patreon/safetynet-fix/v2.1.2?utm_source=github) (for Riru) and [v2.2.0](https://kdrag0n.dev/patreon/safetynet-fix/v2.2.0?utm_source=github) (for Zygisk).

**Closed by kdrag0n** 2021-10-31 04:08 UTC
