### ISSUE TITLE
Response Payload Validation Failed

### ISSUE THREAD

**Issue by Praxtical** [kdrag0n/safetynet-fix#94] opened 2021-09-17 13:25 UTC
Hello! Not sure why this is happening but im not failing any of the ctl or basic checks but the response payload validiation is failing. It also takes up to 40 seconds to check safteynet on any that that isnt magisk and magisk is the only one that doesnt have the response payload validation fail. I thought it was because of lsposed so i uninstalled the module and the manager but to no avail. All I have running is props config and im not even sure if its neccesary or if its causing the fail in the first place.

**Comment by kdrag0n** [comment] 2021-10-31 06:27
This could happen due to a plethora of transient issues and nobody else has reported this, so I'm closing it as an issue that's probably not related to Universal SafetyNet Fix.

**Closed by kdrag0n** 2021-10-31 06:27 UTC

**Comment by kdrag0n** [comment] 2021-10-31 08:16
Actually, this can also be caused by using a SafetyNet checker app with an exhausted API quota. In that case, try another app such as [YASNAC](https://play.google.com/store/apps/details?id=rikka.safetynetchecker) and it should work fine.
